### ISSUE TITLE
Add support for Flask 2.

### ISSUE THREAD

**Issue by SuperSonicHub1** [zgoda/flask-rollup#6]
In `setup.py`:
```
install_requires=[
        'Flask>=1.1,<2'
    ]
```
Pretty sure adding support for Flask 2 shouldn't require any changes on your part.
https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0

**Comment by zgoda** [comment]
Released as 0.3.0. Thanks for the report!

**Comment by SuperSonicHub1** [comment]
Thank you!
